In [9]:
import numpy as np
from sklearn.model_selection import train_test_split


X, y = np.arange(10).reshape((5, 2)), range(5)
print(X, y)
print()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train, y_train)
print()
print(X_test, y_test)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] range(0, 5)

[[8 9]
 [4 5]
 [0 1]
 [6 7]] [4, 2, 0, 3]

[[2 3]] [1]
